In [2]:
%pip install sentence-transformers



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 2.7 MB/s 
     |████████████████████████████████| 5.8 MB 8.7 MB/s 
     |████████████████████████████████| 1.3 MB 45.1 MB/s 
     |████████████████████████████████| 182 kB 56.8 MB/s 
     |████████████████████████████████| 7.6 MB 42.9 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=acba9da802e8c24c93724e0c0ca2f4631ca34a16e5bab8e3279e5eba0f27caf9
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


In [3]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

In [4]:
model = SentenceTransformer('stsb-roberta-large')

Downloading:   0%|          | 0.00/748 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/191 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.92k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/674 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/798k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

In [5]:
s1 = "Humpty Dumpty sat on a wall"
s2 = "Humpty Dumpty had a great fall"
s3 = "Robert DeNiro sat on a wall"

In [6]:
e1 = model.encode(s1, convert_to_tensor=True)
e2 = model.encode(s2, convert_to_tensor=True)
e3 = model.encode(s3, convert_to_tensor=True)

In [10]:
util.pytorch_cos_sim(e1, e2)

tensor([[0.5257]])

In [11]:
util.pytorch_cos_sim(e2, e3)

tensor([[0.1264]])

In [12]:
util.pytorch_cos_sim(e1, e3)

tensor([[0.4475]])

In [13]:
%pip install english-words

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.1 MB 4.1 MB/s 
  Created wheel for english-words: filename=english_words-1.1.0-py3-none-any.whl size=1106679 sha256=d0b884b06c4d4fc7a61189115d2c5c99d6f0a6be6111910d9eeadedc0b217602
  Stored in directory: /root/.cache/pip/wheels/e2/38/3c/b74099fc9935626eaa66b3a7db38d6f1eeb084648e6094e51f
Successfully built english-words


In [14]:
from english_words import english_words_set

In [16]:
english_words_list = list(english_words_set)

In [18]:
from google.colab import drive
drive.mount('/content/drive')


m_words = "/content/drive/MyDrive/cs260project/prompts.rtf"

with open(m_words) as file:
    lines = [line.rstrip()[:-1] for line in file]



Mounted at /content/drive


In [23]:
lines = lines[8:-1]

In [29]:
all_words_embeddings = model.encode(lines, convert_to_tensor=True)

In [32]:
word = "to the right"
selected_embedding = model.encode(word, convert_to_tensor=True)

cos_scores = util.pytorch_cos_sim(selected_embedding, all_words_embeddings)[0]

num_results = 10
top_results = np.argpartition(-cos_scores, range(num_results))[0:num_results]
print("The next ajective shoudl involve the words:")
for idx in top_results[0:num_results]:
    print(lines[idx], "(Score: %.4f)" % (cos_scores[idx]))

The next ajective shoudl involve the words:
to the right (Score: 1.0000)
in red (Score: 0.7650)
turned around (Score: 0.4652)
but round (Score: 0.4602)
looking purple (Score: 0.4331)
in purple (Score: 0.4043)
as r2d2 (Score: 0.3957)
in a house (Score: 0.3553)
in orange (Score: 0.3540)
with stripes (Score: 0.3223)
